// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvzelvpiksfuquyjdudg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52emVsdnBpa3NmdXF1eWpkdWRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4OTQ1ODYsImV4cCI6MjA2MDQ3MDU4Nn0.-g_ymh5-2-1zHCTntrxpYZPoOwbXwa6Ecg9rmJBfh50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);